[project]
name = "agent-utils"
version = "0.1.0"
description = "Package for AI agent utilities."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "logfire>=3.9.0",
    "pydantic>=2.10.6",
    "pydantic-ai>=0.0.41",
]
